### ISSUE TITLE
bower_components and relative imports

### ISSUE THREAD

**Issue by marchenko1985** [oyejorge/less.php#108]
I just have tried your library and got error:

`File "../../../bower_components/bootstrap/less/variables.less" not found. in styles.less`

I tried to compile my `styles.less` which includes twitters bootstrap files from another directory

I have tried to play with `SetImportDirs` with no success

I really hope that this is my misunderstood of given documentation or documentation missing rather than bug

**Comment by korobochkin** [comment]
And how to use relative path with two dots?
