### ISSUE TITLE
Support variable selectors

### ISSUE THREAD

**Issue by twoixter** [oyejorge/less.php#147]
Support for variable selectors. Example:

```
.arrow(@where: after)
{
    &:@{where} {
        content: "V";
    }
}

.arrowed {
    .arrow(before);
}
```

Should generate:

```
.arrowed:before {
    content: "V";
}
```

Now it throws "ParseError: Unexpected input in test.less on line 3, column 5"

**Comment by mmenozzi** [comment]
less.js implements this but less.php don't
