### ISSUE TITLE
Can we reference the version of LESS currently supported?

### ISSUE THREAD

**Issue by rtheunissen** [oyejorge/less.php#156]
It appears to me that less.php doesn't use the lessc npm binary, so whenever they extend their features, it's up to less.php to match them. It's just not clear to me what version of the official binary is currently supported.

Would be useful to have a single line at the top saying "*Equivalent to LESS v1.7.1*" maybe.

**Comment by oyejorge** [comment]
Already does. v1.7.0.7 of Less.php is built off of Less.js 1.7.0
