### ISSUE TITLE
Overriding LESS variables set in files

### ISSUE THREAD

**Issue by thewebists** [oyejorge/less.php#162]
Hi guys, I'm using your compiler in WordPress to compile and configure Bootstrap.

Based on the Bootstrap section in your documentation at http://lessphp.gpeasy.com/ I gather that I should be able to override the Bootstrap variables with my own when using `addVariable()` or `setVariables()`. Am I correct in this assumption?

If so, then the compiler does not do this and the value set using the above functions is overwritten by the value coming from the LESS files.

I've traced this problem to `_parse()` in Parser.php on line 452:
```php
	private function _parse( $file_path = null ){
		if (ini_get("mbstring.func_overload")) {
			$mb_internal_encoding = ini_get("mbstring.internal_encoding");
			@ini_set("mbstring.internal_encoding", "ascii");
		}

		$this->rules = array_merge($this->rules, $this->GetRules( $file_path ));

		//reset php settings
		if (isset($mb_internal_encoding)) {
			@ini_set("mbstring.internal_encoding", $mb_internal_encoding);
		}
	}
```
The problem is with `array_merge($this->rules, $this->GetRules( $file_path ))` as the array_merge function works like this: "If the input arrays have the same string keys, then the later value for that key will overwrite the previous one."

So in this case, the rules coming from the LESS files take precedence to the ones being passed to the compiler during runtime.

The logic I would expect from the compiler would be for the runtime values to take precedence. Or at the very least, I would want this to be a configurable option.

**Comment by elboletaire** [comment]
I had some problems using `ModifyVars` but I think I was using it wrong... Just use the `ModifyVars` after you have parsed the file:

```php
$lessc = new \Less_Parser($options);

$lessc->parseFile($file, $path);
$lessc->ModifyVars($modify_vars);
```

And it will work.

**Comment by oyejorge** [comment]
Yes, using `ModifyVars` after will work. Just remember that precedence in LESS works very much like CSS: the sequence of declaration is significant. Setting variables first will set defaults, setting variables after will overrule what has already been set.
