### ISSUE TITLE
New stable release?

### ISSUE THREAD

**Issue by elboletaire** [oyejorge/less.php#199]
What about a new stable release? Lastest stable version (1.7.0.2) was in june and I know there are code improvements that could be released in a new *flagrant* release :smile:

**Comment by oyejorge** [comment]
[Here it is](https://github.com/oyejorge/less.php/releases/tag/v1.7.0.3)

**Comment by elboletaire** [comment]
*C'est magnifique!*

**Comment by elboletaire** [comment]
BTW, you should consider following semver specs (you have an issue open for this #155)

:smile:
