### ISSUE TITLE
@import doesn't work once on file

### ISSUE THREAD

**Issue by AngeIII** [oyejorge/less.php#202]
File: start.less:
```
   @import "next.less";
   @import "last.less";
```

File: next.less
```
a {
color: red
}
@import "third.less";
```

File: third.less
```
.icon {
 color: blue;
}
```

File: last.less
```
.last {
 display: none;
}
@import "third.less";
```

By using php less:
```
a {
  color: red;
}
.icon {
  color: blue;
}
.last {
  display: none;
}
.icon {
  color: blue;
}
```

but by using default lessc:
```
#>lessc start.less
a {
  color: red;
}
.icon {
  color: blue;
}
.last {
  display: none;
}
```

I tried by adding (once) label in
```
@import (once) "third.less";
```
same result.

**Comment by AngeIII** [comment]
AS investigated by xdebug:
```
		$path = Less_Parser::winPath(realpath($path));
```
causes a problem.

Basicly I use related paths when compiles function\Less_Parser::AddParsedFile
accepts a relative path:  $file = less/third.less
because \Less_Parser::parseFile line 331: $filename = self::WinPath($filename); - this is bug.

and when checking: \Less_Parser::FileParsed accepts full path: $file = /srv/www/wordpress-default/lib/less/third.less

**Comment by AngeIII** [comment]
Looks like \Less_Tree_Import::Skip
should be
```php
			return isset($this->options['multiple']) && $env->importMultiple;
```
Note __! removed__

**Comment by AngeIII** [comment]
@oyejorge issue still exists in latest master.

**Comment by AngeIII** [comment]
```
+			return ( ( isset($this->options['multiple']) && !$this->options['multiple'] ) || !isset($this->options['multiple']) ) && !$env->importMultiple;

```
this is really important fix.

**Comment by oyejorge** [comment]
Hmm, your unit test passed without that line change. Do you have another test?

**Comment by AngeIII** [comment]
I think this is depended by machine, maybe in linux everything is good.
