### ISSUE TITLE
Variables containing relative paths are evaluated at time of use, not time of assignment

### ISSUE THREAD

**Issue by ravisorg** [oyejorge/less.php#213]
This might be an issue with Less itself (vs with Less.php) or might not even be an issue at all if it was designed that way, but I can't find any docs one way or the other on the subject.

For example:

/less/mysite.less
````
@iconSpritePath:          "../lib/bootstrap/img/glyphicons-halflings.png";
````

/lib/bootstrap/less/sprites.less
````
[class^="icon-"],
[class*=" icon-"] {
  background-image: url("@{iconSpritePath}");
}
````

This results in the background image being relative to sprites.less (/lib/bootstrap/less/../lib/bootstrap/img/glyphicons-halflings.png) when I would have expected it to be relative to mysite.less (/less/../lib/bootstrap/img/glyphicons-halflings.png).

In other words, I was expecting the relative path to be evaluated at the time it was set, and from the file it was set in, similar to how relative paths work when they aren't contained in a variable. Using url("../img/glyphicons-halflings.png") in /lib/bootstrap/less/sprites.less would have resulted in the correct URL, so it would stand to reason that whenever a relative URL is specified, it's relative to the file it was specified in.

The reason this is an issue is you may want to set common paths in your main less file and then have them used in other less files, and if those other less files are in different levels of subdirectories it won't work.

There are workarounds, yes, absolute paths being one (although that breaks directory versioning). 

Is this a bug in Less.php? A bug in Less.js? Or is this how it was designed to work and just isn't documented anywhere (or documented somewhere, but I failed miserably at finding it)?

**Comment by seven-phases-max** [comment]
This is by design. `@var: "../some-path";` is just a string, it becomes a path only when you put it inside `url` (or `data-uri`) or so.

**Comment by ravisorg** [comment]
Ahh yes, of course that makes perfect sense. Less doesn't know it's a path until it's used as a path.

And your workaround is brilliant, thank you! :D
