### ISSUE TITLE
How to move mediawiki to this compiler

### ISSUE THREAD

**Issue by paladox** [oyejorge/less.php#226]
Hi mediawiki still uses this compile but I would like to migrate to this one how can it be done. https://github.com/leafo/lessphp mediawiki less file is located at https://git.wikimedia.org/tree/mediawiki%2Fvendor/a30ea32d228ea37447bda49fca8ad7db6d5b2888/leafo%2Flessphp and the rest to load less is done in mediawiki core. I read that you can transition easly but following instructions doesent work just shows a white screen not css is loaded.

**Comment by s7eph4n** [comment]
Mediawiki uses non-standard less code to work around leafo/lessphp bugs. As far as I remember this concerns in particular the paths used in import statement that are not properly handled by the old compiler.

**Comment by paladox** [comment]
But also it carnt upgrade to this without it changing its licencse it needs to be GPL2 compatible which its not.

**Comment by paladox** [comment]
https://phabricator.wikimedia.org/T486
