### ISSUE TITLE
Wrong default relative URL

### ISSUE THREAD

**Issue by sagikazarmark** [oyejorge/less.php#243]
I open this issue in the hope that the authors take it seriously...given that there are already 4 issue/PR open related to this problem.

These are:

- #185
- #142
- #184
- #187

The problem is that the `relativeUrls` option is true by default (confirmed, hard coding it to false solves the problem). In case the package is used as a replacement for [leafo/lessphp](http://leafo.net/lessphp/) (meaning using the `lessc` class) this option cannot be modified.

Currently the only solution I found is to modify the URLs to be absolute ones. This can be done in most cases by modifying variables:

- Bootstrap icon fonts: `@icon-font-path: "/assets/fonts/";`
- Fontawesome icon fonts: `@fa-font-path: "/assets/fonts/";`

**Comment by oyejorge** [comment]
Just pulled the changes from #187. Do we need to change lessc any more?

**Comment by sagikazarmark** [comment]
I don't know which is the default behavior in the "original" lessc. If it parses the URLs correctly aka. with relativeUrls false, then it should be a default setting in this lessc as well (for full compatibility).

**Comment by oyejorge** [comment]
According to #241, relativeUrls should default to false

**Comment by sagikazarmark** [comment]
Then merging that PR as well will solve the issue completely.
