### ISSUE TITLE
Failed to start session after update to 1.7.0.8

### ISSUE THREAD

**Issue by rehoehle** [oyejorge/less.php#255]
If i update to the latest version i get the following error in SF2 and the page isn't loading. I think there is an output caused by this plugin. It's only in the dev mode. 

    Failed to start the session because headers have already been sent by     "/xxxx/vendor/oyejorge/less.php/lib/Less/Version.php" at line 1.

**Comment by oyejorge** [comment]
Sorry about that. Somehow a space character made it into the Version.php file. I'll send out 1.7.0.9 with the fix

**Comment by rehoehle** [comment]
Thx for fixing the problem its working :+1:
