### ISSUE TITLE
"ParseError: Unexpected input" with negative value and "!ie" keyword

### ISSUE THREAD

**Issue by bd808** [oyejorge/less.php#259]
This less:
```
#p-search {
  margin: 2px !ie;
}
```
produces this css:
```
#p-search {
  margin: 2px !ie;
}
```

However this less:
```
#p-search {
  margin: -2px !ie;
}
```
produces this parser error:
```
exception 'Less_Exception_Chunk' with message 'ParseError: Unexpected input in foo.less on line 2, column 3
1| #p-search {
2|   margin: -2px !ie;
3| }
4| ' in /Users/bd808/projects/3rd-party/less.php/lib/Less/Parser.php:543
Stack trace:
#0 /Users/bd808/projects/3rd-party/less.php/lib/Less/Parser.php(487): Less_Parser->GetRules('/Users/bd808/pr...')
#1 /Users/bd808/projects/3rd-party/less.php/lib/Less/Parser.php(364): Less_Parser->_parse('/Users/bd808/pr...')
#2 /Users/bd808/projects/3rd-party/less.php/foo.php(6): Less_Parser->parseFile('foo.less', 'http://example....')
#3 {main}
```

The `!ie` keyword here is intentionally broken CSS syntax that MediaWiki (and probably other crusty old codebases) use to mark IE6/7-speciific CSS.

**Comment by oyejorge** [comment]
[Unfortunately, according to less.js, that is invalid less](http://less2css.org/#{%22less%22%3A%22%23p-search%20{%20%20margin%3A%20-2px%20!ie%3B}%22})

**Comment by bd808** [comment]
The proper solution of using escaping (eg `~"!ie"`) was suggested in the [upstream bug report](https://github.com/less/less.js/issues/2704#issuecomment-144125066).
