### ISSUE TITLE
Hardcoded relativeUrls set to false

### ISSUE THREAD

**Issue by Gappa** [oyejorge/less.php#260]
I have no issue with this option being set to ´false´ by default  (AFAIK original less.js does this by default too), but isn't hardcoding it in the ´getOptions´ method a bit too harsh?

Now we can't easily change the behaviour if we need to - especially if less.php is loaded via composer.

Issues:
* https://github.com/oyejorge/less.php/issues/243
* https://github.com/oyejorge/less.php/pull/239

Commit:
* https://github.com/oyejorge/less.php/commit/0b7a458bde6b6a9028e40cbbfdb68f1e038cbcf3

**Comment by oyejorge** [comment]
One discussion at a time is enough. #239
