### ISSUE TITLE
Enable Source Maps from `lessc` class

### ISSUE THREAD

**Issue by oncletom** [oyejorge/less.php#277]
Hello,

I realised through a [question asked about the wp-less plugin](https://wordpress.org/support/topic/sourcemaps) there was no way to enable Source Maps from the `lessc` class. From what I understand, this class only forwards `formatterName` to `Less_Parser`.

Do you have plans to forward additional options to `Less_Parser`, as all its arguments are provided by `$this->getOptions()`?

Thanks a lot :-)

**Comment by oyejorge** [comment]
Probably not, the lessc.inc.php adapter was only developed to help transition from the leafo/lessphp package. 

To get access to all the features/options available in less, use `$parser = new Less_Parser();`

**Comment by oncletom** [comment]
:+1: gotcha

Thanks for the information — will probably move on supporting the `Less_Parser` only then.

Cheers!
