### ISSUE TITLE
Less_Cache: Regenerate cached sources on parser options change

### ISSUE THREAD

**Issue by ivantcholakov** [oyejorge/less.php#290]
For now I need the following compilation options: 'compress' and 'relativeUrls'. When I use the compiler "on-the-fly", with caching, I noticed that when I change the compiler option 'compress', the generated output does not change, i.e. the LESS cache is not sensible to $parser_options change.

I think, the cache should regenerate in such cases, triggering could be based also on a previously stored value, for example:
sha1(serialize($parser_options))

**Comment by oyejorge** [comment]
Should be fixed by #295

**Comment by ivantcholakov** [comment]
I doubt that #295 implements this feature, because the generated $hash does not depend on $parser_options at all.
