### ISSUE TITLE
Support @font-face

### ISSUE THREAD

**Issue by stormfly-pl** [oyejorge/less.php#297]
Hello,
Can you add @font-face support? It requires only to uncomment code in the Parser.php.

**Comment by seven-phases-max** [comment]
Could you elaborate? Actually `@font-face` is supported by `less.php` just fine. ([The comment](https://github.com/oyejorge/less.php/blob/master/lib/Less/Parser.php#L2101) is only to list some "known" at-rules that will be parsed as "unknown" and known to be OK this way.)

**Comment by stormfly-pl** [comment]
I'm sorry. My mistake. Everything is ok. You can close issue.
