### ISSUE TITLE
Minimal example that uses BOTH css caching AND parser caching?

### ISSUE THREAD

**Issue by rulatir** [oyejorge/less.php#333]
The introduction page shows examples of CSS caching and parser caching, but not both at the same time. I have trouble understanding how the two work together. Does `Less_Cache` **generate** and cache CSS by **automatically invoking** `Less_Parser`, or does it somehow need to be **fed** compiled CSS previously generated with `Less_Parser`? This is unclear.

If the former, is it possible to specify a different cache directory for CSS caching and parser caching?

**Comment by PhrozenByte** [comment]
Shouldn't this be clear from the examples? You pass paths to LESS files into `Less_Cache` and it returns the name of a compiled CSS file, it obviously has to invoke `Less_Parser`. :wink:

If you use `Less_Cache`, it implicitly enables and uses parser caching. You can either use parser caching only, or both CSS caching and parser caching. The `Less_Cache` class is no more than a wrapper to `Less_Parser`'s caching by writing the compiled CSS to a file. Naturally it does this only when `Less_Parser` reports that one of the LESS files have been changed.

**Comment by rulatir** [comment]
Thank you! Reading ability failure on my part notwithstanding, I think it would be clearer if the section on parser caching preceded the section on CSS caching.

**Comment by PhrozenByte** [comment]
@rulatir: You can open a PR and help improving the section, less.php is free software! :smiley: Developers sometimes get a bit stuck in a rut (:laughing:), thus it's even better when someone else does this.
