### ISSUE TITLE
Last release broke PHP 5.3 compatibility

### ISSUE THREAD

**Issue by kylekatarnls** [oyejorge/less.php#345]
Hi,

Can you please tag a new version, because this comes after the last tag: https://github.com/oyejorge/less.php/commit/a05ca596a2c20781ea6f672e19523c43dd68b08f

And so composer update break PHP 5.3 compatibility.

Thanks,

**Comment by Asenar** [comment]
is that ok ?

**Comment by kylekatarnls** [comment]
Perfect all tests pass on my project. Thanks!
