### ISSUE TITLE
Why has the master been renamed asenar/less.php?

### ISSUE THREAD

**Issue by rene-s** [oyejorge/less.php#346]
#Hello,

why has the master been renamed asenar/less.php? Was this done on purpose? 

I am running into all kinds of problems here: 

1. When I require "oyejorge/less.php", the package cannot be found. 
2. When I require "asenar/less.php", the package gets installed to "vendor/asenar" but because version 1.7 is still named "oyejorge/less.php" Composer is trying to find the package in "vendor/oyejorge" which does not exist.

I would appreciate either an acknowledgement that this is indeed a bug (I would gladly prepare a PR then) or a brief explanation on why this has been done and how to fix my problem, thanks!

Regards
Rene 

edit:typos

**Comment by kylekatarnls** [comment]
Hi, until the fix, you can require `kylekatarnls/less.php` I forked it for my own project.

**Comment by Asenar** [comment]
Hi,

it's a mistake, sorry for that, Oyejorge gave me some access (it's in an other issue here) so I merged my works here but I didn't restored his package name.

Sorry about that :/

Also, I don't have access to some settings for publishing to composer or adding travis so I can't really do a lot of thing.

Tell me if what I push fixed your problem.

**Comment by rene-s** [comment]
Hello, thanks for responding and fixing the issue so quickly! 

Regards
Rene
