### ISSUE TITLE
Compression when using caching

### ISSUE THREAD

**Issue by jeffrey-vella** [oyejorge/less.php#5]
It seems like option to turn on compression is not working when using caching mode.

The following works, i can see the output with whitespace and comments removed.

```
$options = array( 'compress'=>true );
$parser = new Less_Parser($options);        
$parser->parseFile( 'C:/inetpub/phproot/TestWordPress/wp-content/themes/carrington-jam-1.4/css/core.less', get_bloginfo('template_url') );          
echo $parser->getCSS();
```

But this doesn't, the created .css file includes comments/whitespace.

```
$options = array( 'compress'=>true );
$parser = new Less_Parser($options);  
$to_cache = array( get_template_directory().'/css/core.less' => get_bloginfo('template_url') );
$upload_folder = '/wp-less-cache/';
$upload_path = wp_upload_dir()['basedir'].$upload_folder;    
Less_Cache::$cache_dir = $upload_path;
$css_file_name = Less_Cache::Get( $to_cache );
$stylesheet_url = wp_upload_dir()['baseurl'].$upload_folder.$css_file_name;
```

**Comment by kentlee87** [comment]
Hi, Im using version 1.7.0.10. I having the same issues.

Here is my code:
$compiled_css_filename = Less_Cache::Get($less_files, $less_config);

Where $less_files is the array list of my .less files.
The $less_config consists of the following items:
$less_config = array(
    'cache_dir' => 'path/to/cache',
    'compress' => true
);

With the compress mode on, the line and white space is removed. However, the comments are still in there. I tried compile the latest version of bootstrap and font-awesome, the result is same.
