### ISSUE TITLE
Compiler silenty dies when url() is base64 encoded image

### ISSUE THREAD

**Issue by jankus** [oyejorge/less.php#55]
Compiler silently dies and kills the whole application without throwing any errors when the url() gets base64 encoded image string (i.e. data:image/png;base64,fooblarandomletters...) instead of a path. Browser cannot even close the connection with an application.

As far as I went it dies somewhere in parsePrimary() method.

**Comment by fdog** [comment]
It's die (again) on long base64 backgrounds:
`background-image: url("data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjwhLS0gQ3JlYXRlZCB3aXRoIElua3NjYXBlIChodHRwOi8vd3d3Lmlua3NjYXBlLm9yZy8pIC0tPgoKPHN2ZwogICB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iCiAgIHhtbG5zOmNjPSJodHRwOi8vY3JlYXRpdmVjb21tb25zLm9yZy9ucyMiCiAgIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyIKICAgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICAgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIgogICB4bWxuczpzb2RpcG9kaT0iaHR0cDovL3NvZGlwb2RpLnNvdXJjZWZvcmdlLm5ldC9EVEQvc29kaXBvZGktMC5kdGQiCiAgIHhtbG5zOmlua3NjYXBlPSJodHRwOi8vd3d3Lmlua3NjYXBlLm9yZy9uYW1lc3BhY2VzL2lua3NjYXBlIgogICB3aWR0aD0iNDgiCiAgIGhlaWdodD0iNDgiCiAgIHZpZXdCb3g9IjAgMCA0OCA0OC4wMDAwMDEiCiAgIGlkPSJzdmcyIgogICB2ZXJzaW9uPSIxLjEiCiAgIGlua3NjYXBlOnZlcnNpb249IjAuOTEgcjEzNzI1IgogICBzb2RpcG9kaTpkb2NuYW1lPSJsb2FkLXBsdXMuc3ZnIj4KICA8ZGVmcwogICAgIGlkPSJkZWZzNCI+CiAgICA8Y2xpcFBhdGgKICAgICAgIGlkPSJjbGlwUGF0aDMzNTYiCiAgICAgICBjbGlwUGF0aFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+CiAgICAgIDxwYXRoCiAgICAgICAgIGlua3NjYXBlOmNvbm5lY3Rvci1jdXJ2YXR1cmU9IjAiCiAgICAgICAgIGlkPSJwYXRoMzM1OCIKICAgICAgICAgZD0ibSAwLDU0LjY3NyA1NC42NzcsMCBMIDU0LjY3NywwIDAsMCAwLDU0LjY3NyBaIiAvPgogICAgPC9jbGlwUGF0aD4KICAgIDxjbGlwUGF0aAogICAgICAgaWQ9ImNsaXBQYXRoMzM2OCIKICAgICAgIGNsaXBQYXRoVW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KICAgICAgPHBhdGgKICAgICAgICAgaW5rc2NhcGU6Y29ubmVjdG9yLWN1cnZhdHVyZT0iMCIKICAgICAgICAgaWQ9InBhdGgzMzcwIgogICAgICAgICBkPSJtIDAsNTQuNjc3IDU0LjY3NywwIEwgNTQuNjc3LDAgMCwwIDAsNTQuNjc3IFoiIC8+CiAgICA8L2NsaXBQYXRoPgogICAgPGNsaXBQYXRoCiAgICAgICBpZD0iY2xpcFBhdGgzMzgwIgogICAgICAgY2xpcFBhdGhVbml0cz0idXNlclNwYWNlT25Vc2UiPgogICAgICA8cGF0aAogICAgICAgICBpbmtzY2FwZTpjb25uZWN0b3ItY3VydmF0dXJlPSIwIgogICAgICAgICBpZD0icGF0aDMzODIiCiAgICAgICAgIGQ9Im0gMCw1NC42NzcgNTQuNjc3LDAgTCA1NC42NzcsMCAwLDAgMCw1NC42NzcgWiIgLz4KICAgIDwvY2xpcFBhdGg+CiAgICA8Y2xpcFBhdGgKICAgICAgIGlkPSJjbGlwUGF0aDMzOTIiCiAgICAgICBjbGlwUGF0aFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+CiAgICAgIDxwYXRoCiAgICAgICAgIGlua3NjYXBlOmNvbm5lY3Rvci1jdXJ2YXR1cmU9IjAiCiAgICAgICAgIGlkPSJwYXRoMzM5NCIKICAgICAgICAgZD0ibSAwLDU0LjY3NyA1NC42NzcsMCBMIDU0LjY3NywwIDAsMCAwLDU0LjY3NyBaIiAvPgogICAgPC9jbGlwUGF0aD4KICAgIDxjbGlwUGF0aAogICAgICAgaWQ9ImNsaXBQYXRoMzQwNCIKICAgICAgIGNsaXBQYXRoVW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KICAgICAgPHBhdGgKICAgICAgICAgaW5rc2NhcGU6Y29ubmVjdG9yLWN1cnZhdHVyZT0iMCIKICAgICAgICAgaWQ9InBhdGgzNDA2IgogICAgICAgICBkPSJtIDAsNTQuNjc3IDU0LjY3NywwIEwgNTQuNjc3LDAgMCwwIDAsNTQuNjc3IFoiIC8+CiAgICA8L2NsaXBQYXRoPgogICAgPGNsaXBQYXRoCiAgICAgICBpZD0iY2xpcFBhdGgzNDE2IgogICAgICAgY2xpcFBhdGhVbml0cz0idXNlclNwYWNlT25Vc2UiPgogICAgICA8cGF0aAogICAgICAgICBpbmtzY2FwZTpjb25uZWN0b3ItY3VydmF0dXJlPSIwIgogICAgICAgICBpZD0icGF0aDM0MTgiCiAgICAgICAgIGQ9Im0gMCw1NC42NzcgNTQuNjc3LDAgTCA1NC42NzcsMCAwLDAgMCw1NC42NzcgWiIgLz4KICAgIDwvY2xpcFBhdGg+CiAgICA8Y2xpcFBhdGgKICAgICAgIGlkPSJjbGlwUGF0aDM0MjgiCiAgICAgICBjbGlwUGF0aFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+CiAgICAgIDxwYXRoCiAgICAgICAgIGlua3NjYXBlOmNvbm5lY3Rvci1jdXJ2YXR1cmU9IjAiCiAgICAgICAgIGlkPSJwYXRoMzQzMCIKICAgICAgICAgZD0ibSAwLDU0LjY3NyA1NC42NzcsMCBMIDU0LjY3NywwIDAsMCAwLDU0LjY3NyBaIiAvPgogICAgPC9jbGlwUGF0aD4KICAgIDxjbGlwUGF0aAogICAgICAgaWQ9ImNsaXBQYXRoMzQ0MCIKICAgICAgIGNsaXBQYXRoVW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KICAgICAgPHBhdGgKICAgICAgICAgaW5rc2NhcGU6Y29ubmVjdG9yLWN1cnZhdHVyZT0iMCIKICAgICAgICAgaWQ9InBhdGgzNDQyIgogICAgICAgICBkPSJtIDAsNTQuNjc3IDU0LjY3NywwIEwgNTQuNjc3LDAgMCwwIDAsNTQuNjc3IFoiIC8+CiAgICA8L2NsaXBQYXRoPgogICAgPGNsaXBQYXRoCiAgICAgICBpZD0iY2xpcFBhdGgzNDUyIgogICAgICAgY2xpcFBhdGhVbml0cz0idXNlclNwYWNlT25Vc2UiPgogICAgICA8cGF0aAogICAgICAgICBpbmtzY2FwZTpjb25uZWN0b3ItY3VydmF0dXJlPSIwIgogICAgICAgICBpZD0icGF0aDM0NTQiCiAgICAgICAgIGQ9Im0gMCw1NC42NzcgNTQuNjc3LDAgTCA1NC42NzcsMCAwLDAgMCw1NC42NzcgWiIgLz4KICAgIDwvY2xpcFBhdGg+CiAgICA8Y2xpcFBhdGgKICAgICAgIGlkPSJjbGlwUGF0aDM2MjAiCiAgICAgICBjbGlwUGF0aFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+CiAgICAgIDxwYXRoCiAgICAgICAgIGlua3NjYXBlOmNvbm5lY3Rvci1jdXJ2YXR1cmU9IjAiCiAgICAgICAgIGlkPSJwYXRoMzYyMiIKICAgICAgICAgZD0ibSAwLDU0LjY3NyA1NC42NzcsMCBMIDU0LjY3NywwIDAsMCAwLDU0LjY3NyBaIiAvPgogICAgPC9jbGlwUGF0aD4KICAgIDxjbGlwUGF0aAogICAgICAgaWQ9ImNsaXBQYXRoMzYxMSIKICAgICAgIGNsaXBQYXRoVW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KICAgICAgPHBhdGgKICAgICAgICAgaW5rc2NhcGU6Y29ubmVjdG9yLWN1cnZhdHVyZT0iMCIKICAgICAgICAgaWQ9InBhdGgzNjEzIgogICAgICAgICBkPSJtIDAsODY0LjU2NyA2MTcuOTU4LDAgTCA2MTcuOTU4LDAgMCwwIDAsODY0LjU2NyBaIiAvPgogICAgPC9jbGlwUGF0aD4KICAgIDxjbGlwUGF0aAogICAgICAgaWQ9ImNsaXBQYXRoMzY0MCIKICAgICAgIGNsaXBQYXRoVW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KICAgICAgPHBhdGgKICAgICAgICAgaW5rc2NhcGU6Y29ubmVjdG9yLWN1cnZhdHVyZT0iMCIKICAgICAgICAgaWQ9InBhdGgzNjQyIgogICAgICAgICBkPSJtIDAsNjIzLjYyNyA4NzAuMjM2LDAgTCA4NzAuMjM2LDAgMCwwIDAsNjIzLjYyNyBaIiAvPgogICAgPC9jbGlwUGF0aD4KICAgIDxjbGlwUGF0aAogICAgICAgaWQ9ImNsaXBQYXRoNDQ3NiIKICAgICAgIGNsaXBQYXRoVW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KICAgICAgPHBhdGgKICAgICAgICAgaW5rc2NhcGU6Y29ubmVjdG9yLWN1cnZhdHVyZT0iMCIKICAgICAgICAgaWQ9InBhdGg0NDc4IgogICAgICAgICBkPSJtIDAsODY0LjU2NyA2MTcuOTU4LDAgTCA2MTcuOTU4LDAgMCwwIDAsODY0LjU2NyBaIiAvPgogICAgPC9jbGlwUGF0aD4KICAgIDxjbGlwUGF0aAogICAgICAgaWQ9ImNsaXBQYXRoNDUwMCIKICAgICAgIGNsaXBQYXRoVW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KICAgICAgPHBhdGgKICAgICAgICAgaW5rc2NhcGU6Y29ubmVjdG9yLWN1cnZhdHVyZT0iMCIKICAgICAgICAgaWQ9InBhdGg0NTAyIgogICAgICAgICBkPSJtIDAsODY0LjU2NyA2MTcuOTU4LDAgTCA2MTcuOTU4LDAgMCwwIDAsODY0LjU2NyBaIiAvPgogICAgPC9jbGlwUGF0aD4KICAgIDxjbGlwUGF0aAogICAgICAgaWQ9ImNsaXBQYXRoNDE3NyIKICAgICAgIGNsaXBQYXRoVW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KICAgICAgPHBhdGgKICAgICAgICAgaW5rc2NhcGU6Y29ubmVjdG9yLWN1cnZhdHVyZT0iMCIKICAgICAgICAgaWQ9InBhdGg0MTc5IgogICAgICAgICBkPSJtIDAsODY0LjU2NyA2MTcuOTU4LDAgTCA2MTcuOTU4LDAgMCwwIDAsODY0LjU2NyBaIiAvPgogICAgPC9jbGlwUGF0aD4KICA8L2RlZnM+CiAgPHNvZGlwb2RpOm5hbWVkdmlldwogICAgIGlkPSJiYXNlIgogICAgIHBhZ2Vjb2xvcj0iI2ZmZmZmZiIKICAgICBib3JkZXJjb2xvcj0iIzY2NjY2NiIKICAgICBib3JkZXJvcGFjaXR5PSIxLjAiCiAgICAgaW5rc2NhcGU6cGFnZW9wYWNpdHk9IjAuMCIKICAgICBpbmtzY2FwZTpwYWdlc2hhZG93PSIyIgogICAgIGlua3NjYXBlOnpvb209IjUuNiIKICAgICBpbmtzY2FwZTpjeD0iMTIuOTEwNzE0IgogICAgIGlua3NjYXBlOmN5PSIyMy44Mjg1NDEiCiAgICAgaW5rc2NhcGU6ZG9jdW1lbnQtdW5pdHM9InB4IgogICAgIGlua3NjYXBlOmN1cnJlbnQtbGF5ZXI9ImczNjM0IgogICAgIHNob3dncmlkPSJmYWxzZSIKICAgICB1bml0cz0icHgiCiAgICAgaW5rc2NhcGU6d2luZG93LXdpZHRoPSIxOTIwIgogICAgIGlua3NjYXBlOndpbmRvdy1oZWlnaHQ9IjExMzciCiAgICAgaW5rc2NhcGU6d2luZG93LXg9Ii04IgogICAgIGlua3NjYXBlOndpbmRvdy15PSItOCIKICAgICBpbmtzY2FwZTp3aW5kb3ctbWF4aW1pemVkPSIxIiAvPgogIDxtZXRhZGF0YQogICAgIGlkPSJtZXRhZGF0YTciPgogICAgPHJkZjpSREY+CiAgICAgIDxjYzpXb3JrCiAgICAgICAgIHJkZjphYm91dD0iIj4KICAgICAgICA8ZGM6Zm9ybWF0PmltYWdlL3N2Zyt4bWw8L2RjOmZvcm1hdD4KICAgICAgICA8ZGM6dHlwZQogICAgICAgICAgIHJkZjpyZXNvdXJjZT0iaHR0cDovL3B1cmwub3JnL2RjL2RjbWl0eXBlL1N0aWxsSW1hZ2UiIC8+CiAgICAgICAgPGRjOnRpdGxlPjwvZGM6dGl0bGU+CiAgICAgIDwvY2M6V29yaz4KICAgIDwvcmRmOlJERj4KICA8L21ldGFkYXRhPgogIDxnCiAgICAgaW5rc2NhcGU6bGFiZWw9IkxheWVyIDEiCiAgICAgaW5rc2NhcGU6Z3JvdXBtb2RlPSJsYXllciIKICAgICBpZD0ibGF5ZXIxIgogICAgIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAsLTEwMDQuMzYyMikiPgogICAgPGcKICAgICAgIHRyYW5zZm9ybT0ibWF0cml4KDAuMTA3MTM2MjcsMCwwLC0wLjEwNzEzNjI3LC0xOC4xMDc1ODIsMTA3My42OTM1KSIKICAgICAgIGlua3NjYXBlOmxhYmVsPSJ6b29tIgogICAgICAgaWQ9ImczNjM0Ij4KICAgICAgPHBhdGgKICAgICAgICAgc3R5bGU9ImZpbGw6IzQ0MmQzZjtmaWxsLW9wYWNpdHk6MTtmaWxsLXJ1bGU6bm9uemVybztzdHJva2U6bm9uZSIKICAgICAgICAgZD0ibSAzOTMuMDEwMDIsNTk1LjM1NzkgYyAtOTQuOTcyNSwwIC0xNzIuMjIxNTEsLTc3LjI1NTU4IC0xNzIuMjIxNTEsLTE3Mi4yMzk3NiAwLC05NC45NzI1MSA3Ny4yNDkwMSwtMTcyLjIzOTc1IDE3Mi4yMjE1MSwtMTcyLjIzOTc1IDk0Ljk4NDE5LDAgMTcyLjI1OCw3Ny4yNjcyNCAxNzIuMjU4LDE3Mi4yMzk3NSAwLDk0Ljk4NDE4IC03Ny4yNzM4MSwxNzIuMjM5NzYgLTE3Mi4yNTgsMTcyLjIzOTc2IHogbSAwLC0yMy4zMzQ3NyBjIDgyLjEwMzM4LDAgMTQ4LjkyMzIzLC02Ni44MDE2MSAxNDguOTIzMjMsLTE0OC45MDQ5OSAwLC04Mi4xMDMzOCAtNjYuODE5ODUsLTE0OC45MDQ5OSAtMTQ4LjkyMzIzLC0xNDguOTA0OTkgLTgyLjEwMzM3LDAgLTE0OC44ODY3NSw2Ni44MDE2MSAtMTQ4Ljg4Njc1LDE0OC45MDQ5OSAwLDgyLjEwMzM4IDY2Ljc4MzM4LDE0OC45MDQ5OSAxNDguODg2NzUsMTQ4LjkwNDk5IHogbSAtMTYuMDYwODgsLTYzLjIwNDQxIDAsLTY5LjY1NzkyIC02OS42MjE0NiwwIDAsLTMyLjEyMTc3IDY5LjYyMTQ2LDAgMCwtNjkuNjAzMjQgMzIuMTIxNzgsMCAwLDY5LjYwMzI0IDY5LjYyMTQ2LDAgMCwzMi4xMjE3NyAtNjkuNjIxNDYsMCAwLDY5LjY1NzkyIC0zMi4xMjE3OCwwIHoiCiAgICAgICAgIGlkPSJwYXRoNDE4MyIKICAgICAgICAgaW5rc2NhcGU6Y29ubmVjdG9yLWN1cnZhdHVyZT0iMCIgLz4KICAgIDwvZz4KICA8L2c+Cjwvc3ZnPgo=");`
