### ISSUE TITLE
Compiler shouldn't die if "Less.php cache directory couldn't be created"

### ISSUE THREAD

**Issue by jankus** [oyejorge/less.php#94]
I do understand error, but I suggest changing behavior.

If it is set up to use cache but compiler cannot create tmp folder or any other check related with cache fails, I suggest turn off cache, throw only warning and compile less as if cache wasn't turned on.

This is important to our software. It is distributed with cache on. If a user has disabled mkdir() or permissions doesn't allow to do that, the whole website breaks.

**Comment by Sebi94nbg** [comment]
Is there a fix in the latest version of FreePBX?

I've just installed the latest version and the UCP is just not working. That's a joke for a out-of-the-box installation of such an awesome and worldwide used software, or?

I've already refreshed the signatures and reinstalled the UCP without success.

I want to get this worked, but I don't know how...
